
title: Dungeon Experiment

description: Github pages Dungeon

baseurl: "/rooms/"


# Don't Package these files
# exclude: ["ReadMe.md", "Rakefile", "License.md"]

# Search
lsi: false

safe: true

source: .

# Full Rebuild
incremental: false
highlighter: rouge

gist:
  noscript: false
  
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  rooms:
    output: true